# Generated by Django 2.1.2 on 2018-10-15 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('friends', models.ManyToManyField(related_name='_student_friends_+', to='stopout.Student')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopout.School')),
            ],
        ),
    ]
